/**
 * Centralized registry of every `ConvexError` code thrown by the auth
 * package. Use `ErrorCode.<NAME>` instead of inline string literals so
 * typos surface at compile time and consumers can pattern-match on the
 * union type.
 *
 * Naming: SCREAMING_SNAKE_CASE, scoped by domain prefix where useful
 * (e.g. `OAUTH_*`, `INVITE_*`, `API_KEY_*`).
 *
 * @module
 */

export const ErrorCode = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_PARAMETERS: "INVALID_PARAMETERS",
  INVALID_REDIRECT: "INVALID_REDIRECT",
  FORBIDDEN: "FORBIDDEN",
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  NOT_SIGNED_IN: "NOT_SIGNED_IN",
  RATE_LIMITED: "RATE_LIMITED",
  MISSING_ENV_VAR: "MISSING_ENV_VAR",
  CASCADE_TOO_LARGE: "CASCADE_TOO_LARGE",
  PROVIDER_NOT_CONFIGURED: "PROVIDER_NOT_CONFIGURED",
  INVALID_CREDENTIALS_PROVIDER: "INVALID_CREDENTIALS_PROVIDER",
  MISSING_CRYPTO_FUNCTION: "MISSING_CRYPTO_FUNCTION",

  ACCOUNT_ALREADY_LINKED: "ACCOUNT_ALREADY_LINKED",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  AMBIGUOUS_USER_LINK: "AMBIGUOUS_USER_LINK",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_VERIFIER: "INVALID_VERIFIER",
  VERIFICATION_CODE_COLLISION: "VERIFICATION_CODE_COLLISION",

  API_KEY_EXPIRED: "API_KEY_EXPIRED",
  API_KEY_RATE_LIMITED: "API_KEY_RATE_LIMITED",
  API_KEY_REVOKED: "API_KEY_REVOKED",
  INVALID_API_KEY: "INVALID_API_KEY",
  KEY_NOT_FOUND: "KEY_NOT_FOUND",
  MISSING_BEARER_TOKEN: "MISSING_BEARER_TOKEN",
  SCOPE_CHECK_FAILED: "SCOPE_CHECK_FAILED",

  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",

  OAUTH_CLIENT_NOT_FOUND: "OAUTH_CLIENT_NOT_FOUND",
  OAUTH_CODE_ALREADY_USED: "OAUTH_CODE_ALREADY_USED",
  OAUTH_CODE_EXPIRED: "OAUTH_CODE_EXPIRED",
  OAUTH_GRANT_TYPE_NOT_ALLOWED: "OAUTH_GRANT_TYPE_NOT_ALLOWED",
  OAUTH_INVALID_PROFILE: "OAUTH_INVALID_PROFILE",
  OAUTH_INVALID_REFRESH_TOKEN: "OAUTH_INVALID_REFRESH_TOKEN",
  OAUTH_INVALID_STATE: "OAUTH_INVALID_STATE",
  OAUTH_MISSING_PROVIDER: "OAUTH_MISSING_PROVIDER",
  OAUTH_MISSING_VERIFIER: "OAUTH_MISSING_VERIFIER",
  OAUTH_PROVIDER_ERROR: "OAUTH_PROVIDER_ERROR",
  OAUTH_REDIRECT_URI_MISMATCH: "OAUTH_REDIRECT_URI_MISMATCH",
  OAUTH_SCOPE_NOT_ALLOWED: "OAUTH_SCOPE_NOT_ALLOWED",

  DEVICE_AUTHORIZATION_FAILED: "DEVICE_AUTHORIZATION_FAILED",
  DEVICE_CODE_EXPIRED: "DEVICE_CODE_EXPIRED",

  PASSKEY_NOT_FOUND: "PASSKEY_NOT_FOUND",
  PASSKEY_AUTH_REQUIRED: "PASSKEY_AUTH_REQUIRED",
  PASSKEY_COUNTER_ERROR: "PASSKEY_COUNTER_ERROR",
  PASSKEY_INVALID_CHALLENGE: "PASSKEY_INVALID_CHALLENGE",
  PASSKEY_INVALID_CLIENT_DATA: "PASSKEY_INVALID_CLIENT_DATA",
  PASSKEY_INVALID_ORIGIN: "PASSKEY_INVALID_ORIGIN",
  PASSKEY_INVALID_SIGNATURE: "PASSKEY_INVALID_SIGNATURE",
  PASSKEY_INVALID_VERIFY: "PASSKEY_INVALID_VERIFY",
  PASSKEY_MISSING_CONFIG: "PASSKEY_MISSING_CONFIG",
  PASSKEY_MISSING_FLOW: "PASSKEY_MISSING_FLOW",
  PASSKEY_MISSING_VERIFIER: "PASSKEY_MISSING_VERIFIER",
  PASSKEY_NO_CREDENTIAL: "PASSKEY_NO_CREDENTIAL",
  PASSKEY_RP_MISMATCH: "PASSKEY_RP_MISMATCH",
  PASSKEY_UNKNOWN_CREDENTIAL: "PASSKEY_UNKNOWN_CREDENTIAL",
  PASSKEY_UNSUPPORTED_ALGORITHM: "PASSKEY_UNSUPPORTED_ALGORITHM",
  PASSKEY_USER_PRESENCE: "PASSKEY_USER_PRESENCE",
  PASSKEY_USER_VERIFICATION: "PASSKEY_USER_VERIFICATION",

  TOTP_NOT_FOUND: "TOTP_NOT_FOUND",
  TOTP_ALREADY_VERIFIED: "TOTP_ALREADY_VERIFIED",
  TOTP_AUTH_REQUIRED: "TOTP_AUTH_REQUIRED",
  TOTP_INVALID_CODE: "TOTP_INVALID_CODE",
  TOTP_INVALID_VERIFIER: "TOTP_INVALID_VERIFIER",
  TOTP_MISSING_CODE: "TOTP_MISSING_CODE",
  TOTP_MISSING_FLOW: "TOTP_MISSING_FLOW",
  TOTP_MISSING_VERIFIER: "TOTP_MISSING_VERIFIER",
  TOTP_NO_ENROLLMENT: "TOTP_NO_ENROLLMENT",

  DUPLICATE_INVITE: "DUPLICATE_INVITE",
  DUPLICATE_MEMBERSHIP: "DUPLICATE_MEMBERSHIP",
  INVITE_ALREADY_ACCEPTED: "INVITE_ALREADY_ACCEPTED",
  INVITE_EMAIL_MISMATCH: "INVITE_EMAIL_MISMATCH",
  INVITE_EXPIRED: "INVITE_EXPIRED",
  INVITE_NOT_FOUND: "INVITE_NOT_FOUND",
  INVITE_NOT_PENDING: "INVITE_NOT_PENDING",
  INVALID_ROLE_IDS: "INVALID_ROLE_IDS",
  MISSING_GRANTS: "MISSING_GRANTS",
  NO_ACTIVE_GROUP: "NO_ACTIVE_GROUP",
  NOT_A_MEMBER: "NOT_A_MEMBER",

  GROUP_CONNECTION_DOMAIN_TAKEN: "GROUP_CONNECTION_DOMAIN_TAKEN",
} as const;

/** Union of every {@link ErrorCode} value. */
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
