import { defineComponent } from "convex/server";
import { v } from "convex/values";

/**
 * The core auth component.
 *
 * Owns:
 *  - RS256 signing key + JWKS (stored as env vars, generated by
 *    `npx @convex-dev/auth`)
 *  - the provider-account <-> app-user mapping (`accounts`)
 *  - session lifetimes (`sessions`: refresh tokens, rotation, expiry)
 *
 * It does NOT know about any specific provider. Providers hand it identity
 * claims (see ../../lib/types) and the core turns that into a session + JWT.
 */
const component = defineComponent("auth", {
  env: {
    AUTH_PRIVATE_KEY: v.string(),
    AUTH_JWKS: v.string(),
  },
});

export default component;
