const modules: Record<string, () => Promise<unknown>> = {
  "./component/_generated/api.ts": () => import("./_generated/api"),
  "./component/_generated/component.ts": () => import("./_generated/component"),
  "./component/_generated/dataModel.ts": () => import("./_generated/dataModel"),
  "./component/_generated/server.ts": () => import("./_generated/server"),
  "./component/convex.config.ts": () => import("./convex.config"),
  "./component/crons.ts": () => import("./crons"),
  "./component/functions.ts": () => import("./functions"),
  "./component/http.ts": () => import("./http"),
  "./component/index.ts": () => import("./index"),
  "./component/event.ts": () => import("./event"),
  "./component/limits.ts": () => import("./limits"),
  "./component/maintenance.ts": () => import("./maintenance"),
  "./component/migrations.ts": () => import("./migrations"),
  "./component/model.ts": () => import("./model"),
  "./component/group.ts": () => import("./group"),
  "./component/group/member.ts": () => import("./group/member"),
  "./component/group/invite.ts": () => import("./group/invite"),
  "./component/user/key.ts": () => import("./user/key"),
  "./component/account.ts": () => import("./account"),
  "./component/session.ts": () => import("./session"),
  "./component/token/refresh.ts": () => import("./token/refresh"),
  "./component/token/verification.ts": () => import("./token/verification"),
  "./component/token/pkce.ts": () => import("./token/pkce"),
  "./component/user.ts": () => import("./user"),
  "./component/user/email.ts": () => import("./user/email"),
  "./component/factor/passkey.ts": () => import("./factor/passkey"),
  "./component/factor/totp.ts": () => import("./factor/totp"),
  "./component/factor/device.ts": () => import("./factor/device"),
  "./component/connection.ts": () => import("./connection"),
  "./component/connection/saml/request.ts": () => import("./connection/saml/request"),
  "./component/connection/saml/assertion.ts": () => import("./connection/saml/assertion"),
  "./component/connection/domain.ts": () => import("./connection/domain"),
  "./component/connection/domain/verification.ts": () => import("./connection/domain/verification"),
  "./component/connection/secret.ts": () => import("./connection/secret"),
  "./component/connection/scim/config.ts": () => import("./connection/scim/config"),
  "./component/connection/scim/identity.ts": () => import("./connection/scim/identity"),
  "./component/connection/audit.ts": () => import("./connection/audit"),
  "./component/connection/cache.ts": () => import("./connection/cache"),
  "./component/connection/webhook/endpoint.ts": () => import("./connection/webhook/endpoint"),
  "./component/connection/webhook/delivery.ts": () => import("./connection/webhook/delivery"),
  "./component/oauth/client.ts": () => import("./oauth/client"),
  "./component/oauth/code.ts": () => import("./oauth/code"),
  "./component/oauth/refresh.ts": () => import("./oauth/refresh"),
  "./component/schema.ts": () => import("./schema"),
};

export default modules;
